from models.config.default import _CN as cfg

cfg.S2LD.MATCH_COARSE.MATCH_TYPE = 'dual_softmax'
cfg.S2LD.MATCH_COARSE.SPARSE_SPVS = False
cfg.S2LD.WITH_KP = True

cfg.S2LD.LOSS.KEYPOINT_WEIGHT = 0.1
cfg.S2LD.LOSS.SCORE_WEIGHT = 0.1
cfg.S2LD.LOSS.REPEATABILITY_WEIGHT = 0.1
cfg.S2LD.LOSS.DISTRIBUTION_WEIGHT = 0.5

cfg.TRAINER.CANONICAL_LR = 8e-3
cfg.TRAINER.WARMUP_STEP = 1875  # 3 epochs
cfg.TRAINER.WARMUP_RATIO = 0.1
# cfg.TRAINER.MSLR_MILESTONES = [8, 12, 16, 20, 24]
cfg.TRAINER.MSLR_MILESTONES = [6, 10, 14, 18, 22, 26]

# pose estimation
cfg.TRAINER.RANSAC_PIXEL_THR = 0.5

cfg.TRAINER.OPTIMIZER = "adamw"
cfg.TRAINER.ADAMW_DECAY = 0.1
cfg.TRAINER.ENABLE_PLOTTING = False
cfg.S2LD.MATCH_COARSE.TRAIN_COARSE_PERCENT = 0.3
